// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AosController from "./aos_controller"
application.register("aos", AosController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CardFormController from "./card_form_controller"
application.register("card-form", CardFormController)

import ChatsubmitController from "./chatsubmit_controller"
application.register("chatsubmit", ChatsubmitController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HotkeyController from "./hotkey_controller"
application.register("hotkey", HotkeyController)

import IntroController from "./intro_controller"
application.register("intro", IntroController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NewcardController from "./newcard_controller"
application.register("newcard", NewcardController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
